title: "Kamesh Kotwani"
email: "kameshkotwani@gmail.com"
description: >- # this means to ignore newlines until "baseurl:"
  A Microsoft Azure-certified Data Scientist and Big Data Engineer with a passion for transforming complex data into actionable insights.

twitter_username: kameshkotwani
github_username: kameshkotwani
minimal_mistakes_skin: default
search: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: "Europe/London"

include:
  - _pages


# Set About as Homepage
homepage:
  layout: single
  permalink: /
  title: "About"
  author_profile: true
  content: /about/

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Kamesh Kotwani"
  avatar : "/assets/images/profile_new.jpg"
  bio    : "A Microsoft Azure-certified Data Scientist and Big Data Engineer with a passion for transforming complex data into actionable insights."
  location: "United Kingdom"
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/kameshkotwani"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/kameshkotwani"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/kameshkotwani/"
    

defaults:
  # _homepage
  - scope:
      path: ""
      type: homepage
    values:
      layout: single
      permalink: /
      title: "About"
      author_profile: true
      content: /about/

  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages

  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
