title: "Kamesh Kotwani"
email: "kameshkotwani@gmail.com"
description: >-
  I am a results-driven Data Scientist and Big Data Engineer with a passion for transforming complex data into actionable insights. With an MSc in Data Science from the University of Sheffield and hands-on experience in machine learning, big data, and cloud computing, I specialize in building scalable AI solutions, deploying production-ready ML models, and designing robust data pipelines.

  I am Microsoft Azure-certified (DP-100) and have worked on projects spanning NLP, time-series forecasting, and deep learning, delivering high-impact solutions in healthcare, finance, and analytics. My expertise in Python, Spark, AWS, Azure, Kubernetes, and CI/CD pipelines enables me to bridge the gap between data science and engineering, ensuring end-to-end solutions that drive business growth.

  With experience as a Big Data Engineer at IQVIA and a Machine Learning Engineer at CDAC, I have developed high-performance data pipelines, optimized machine learning workflows, and improved platform reliability. Currently, as a Teaching Assistant at the University of Sheffield, I mentor students in Big Data Analytics, AWS, and Databricks, fostering the next generation of data professionals.

  I thrive in solving real-world challenges using data, continuously learning and leveraging the latest advancements in AI, GenAI, and LLMs. Let’s connect and explore how data-driven strategies can make a difference!

twitter_username: kameshkotwani
github_username: kameshkotwani
minimal_mistakes_skin: default
search: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: "Europe/London"

include:
  - _pages


# Set About as Homepage
homepage:
  layout: single
  permalink: /
  title: "About"
  author_profile: true
  content: /about/

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Kamesh Kotwani"
  avatar : "/assets/images/profile_new.jpg"
  bio    : "A Microsoft Azure-certified Data Scientist and Big Data Engineer with a passion for transforming complex data into actionable insights."
  location: "United Kingdom"
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/kameshkotwani"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/kameshkotwani"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/kameshkotwani/"
    

defaults:
  # _posts
  # - scope:
  #     path: ""
  #     type: posts
  #   values:
  #     layout: single
  #     author_profile: true
  #     read_time: true
  #     comments: true
  #     share: true
  #     related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
  - scope:
      path: ""
      type: homepage
    values:
      layout: single
      permalink: /
      title: "About"
      author_profile: true
      content: /about/

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
