name: Dev Env Workflow

on:
  push:
    branches:
      - 'feat:*'
      - projects-section

jobs:
  build:
    runs-on: ubuntu-latest
    environment: dev-env

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.2.3'

    - name: Install dependencies
      run: |
        gem install bundler
        bundle install

    - name: Build Jekyll site
      run: bundle exec jekyll build
    
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        personal_token: ${{ secrets.DEPLOY_TOKEN_DEV }}  # Use PAT instead of GITHUB_TOKEN
        publish_branch: projects-section  # Ensure this is the correct branch
        publish_dir: ./_site
        force_orphan: true # not sure if this is needed
